/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type AssigneeId = string;
export interface AuthenticatedUser {
  'role' : [] | [string],
  'personnelId' : [] | [PersonnelId],
  'companyId' : [] | [CompanyId],
}
export type Code = string;
export type CompanyId = string;
export type DeadLine = string;
export interface Machine {
  'id' : MachineId,
  'status' : string,
  'name' : string,
  'createdAt' : Timestamp,
  'serialNumber' : string,
  'notes' : string,
  'location' : string,
  'machineType' : string,
  'companyId' : CompanyId,
}
export type MachineId = string;
export type PersonnelId = string;
export interface Project {
  'id' : ProjectId,
  'status' : string,
  'name' : string,
  'createdAt' : Timestamp,
  'description' : string,
  'deadline' : string,
  'companyId' : CompanyId,
}
export type ProjectId = string;
export interface Task {
  'id' : TaskId,
  'status' : string,
  'title' : string,
  'assigneeId' : AssigneeId,
  'dueDate' : DeadLine,
  'projectId' : ProjectId,
  'companyId' : CompanyId,
}
export type TaskId = bigint;
export type Timestamp = bigint;
export interface UserProfile {
  'name' : string,
  'email' : string,
  'personnelId' : [] | [PersonnelId],
  'companyId' : [] | [CompanyId],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface Failure {
  'id' : string,
  'machineId' : string,
  'companyId' : CompanyId,
  'title' : string,
  'description' : string,
  'severity' : string,
  'status' : string,
  'reportedBy' : string,
  'reportedAt' : Timestamp,
  'resolvedAt' : string,
}
export interface FailureWithProject {
  'id' : string,
  'machineId' : string,
  'companyId' : CompanyId,
  'title' : string,
  'description' : string,
  'severity' : string,
  'status' : string,
  'reportedBy' : string,
  'reportedAt' : Timestamp,
  'resolvedAt' : string,
  'projectId' : string,
}
export interface Document {
  'id' : string,
  'companyId' : CompanyId,
  'title' : string,
  'fileName' : string,
  'category' : string,
  'uploadedBy' : string,
  'createdAt' : Timestamp,
}
export interface HseRecord {
  'id' : string,
  'companyId' : CompanyId,
  'hseType' : string,
  'title' : string,
  'description' : string,
  'severity' : string,
  'status' : string,
  'reportedBy' : string,
  'createdAt' : Timestamp,
}
export interface Shipment {
  'id' : string,
  'companyId' : CompanyId,
  'title' : string,
  'machineId' : string,
  'fromLocation' : string,
  'toLocation' : string,
  'carrier' : string,
  'status' : string,
  'shipDate' : string,
  'estimatedDelivery' : string,
  'notes' : string,
  'createdAt' : Timestamp,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addMachine' : ActorMethod<
    [string, string, string, string, string, string],
    string
  >,
  'addPersonnelToCompany' : ActorMethod<[Code, Code, string], undefined>,
  'addTask' : ActorMethod<[string, string, string, string, string], bigint>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'authenticate' : ActorMethod<[Code], [] | [AuthenticatedUser]>,
  'createProject' : ActorMethod<[string, string, string, string], string>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listMachines' : ActorMethod<[string], Array<Machine>>,
  'listProjects' : ActorMethod<[string], Array<Project>>,
  'updateProjectStatus': ActorMethod<[string, string], undefined>,
  'listTasks' : ActorMethod<[string], Array<Task>>,
  'registerCompany' : ActorMethod<
    [string, string],
    { 'id' : CompanyId, 'adminCode' : Code }
  >,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'selfRegisterPersonnel' : ActorMethod<
    [string, string],
    { 'loginCode' : Code, 'inviteCode' : Code }
  >,
  'updateMachineStatus' : ActorMethod<[string, string], undefined>,
  'addFailure' : ActorMethod<[string, string, string, string, string, string, string], string>,
  'listFailures' : ActorMethod<[string], Array<FailureWithProject>>,
  'updateFailureStatus' : ActorMethod<[string, string], undefined>,
  'addDocument' : ActorMethod<[string, string, string, string, string], string>,
  'listDocuments' : ActorMethod<[string], Array<Document>>,
  'deleteDocument' : ActorMethod<[string], undefined>,
  'addHseRecord' : ActorMethod<[string, string, string, string, string, string], string>,
  'listHseRecords' : ActorMethod<[string], Array<HseRecord>>,
  'updateHseStatus' : ActorMethod<[string, string], undefined>,
  'addShipment' : ActorMethod<[string, string, string, string, string, string, string, string, string], string>,
  'listShipments' : ActorMethod<[string], Array<Shipment>>,
  'updateShipmentStatus' : ActorMethod<[string, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];
