/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Code = IDL.Text;
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const PersonnelId = IDL.Text;
export const CompanyId = IDL.Text;
export const AuthenticatedUser = IDL.Record({
  'role' : IDL.Opt(IDL.Text),
  'personnelId' : IDL.Opt(PersonnelId),
  'companyId' : IDL.Opt(CompanyId),
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'personnelId' : IDL.Opt(PersonnelId),
  'companyId' : IDL.Opt(CompanyId),
});
export const Timestamp = IDL.Int;
export const Personnel = IDL.Record({
  'id' : PersonnelId,
  'loginCode' : Code,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'role' : IDL.Text,
  'inviteCode' : Code,
  'companyId' : IDL.Opt(CompanyId),
});
export const DocumentId = IDL.Text;
export const Document = IDL.Record({
  'id' : DocumentId,
  'title' : IDL.Text,
  'createdAt' : Timestamp,
  'fileName' : IDL.Text,
  'category' : IDL.Text,
  'uploadedBy' : IDL.Text,
  'companyId' : CompanyId,
});
export const FailureId = IDL.Text;
export const MachineId = IDL.Text;
export const FailureWithProject = IDL.Record({
  'id' : FailureId,
  'status' : IDL.Text,
  'title' : IDL.Text,
  'description' : IDL.Text,
  'reportedAt' : Timestamp,
  'reportedBy' : IDL.Text,
  'projectId' : IDL.Text,
  'severity' : IDL.Text,
  'machineId' : MachineId,
  'resolvedAt' : IDL.Text,
  'companyId' : CompanyId,
});
export const HseId = IDL.Text;
export const HseRecord = IDL.Record({
  'id' : HseId,
  'status' : IDL.Text,
  'title' : IDL.Text,
  'hseType' : IDL.Text,
  'createdAt' : Timestamp,
  'description' : IDL.Text,
  'reportedBy' : IDL.Text,
  'severity' : IDL.Text,
  'companyId' : CompanyId,
});
export const Machine = IDL.Record({
  'id' : MachineId,
  'status' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'serialNumber' : IDL.Text,
  'notes' : IDL.Text,
  'location' : IDL.Text,
  'machineType' : IDL.Text,
  'companyId' : CompanyId,
});
export const MaintenancePlanId = IDL.Text;
export const MaintenancePlan = IDL.Record({
  'id' : MaintenancePlanId,
  'status' : IDL.Text,
  'title' : IDL.Text,
  'assignedTo' : IDL.Text,
  'createdAt' : Timestamp,
  'description' : IDL.Text,
  'frequency' : IDL.Text,
  'machineId' : IDL.Text,
  'nextDate' : IDL.Text,
  'companyId' : CompanyId,
});
export const ProjectAssignmentId = IDL.Text;
export const ProjectId = IDL.Text;
export const ProjectAssignment = IDL.Record({
  'id' : ProjectAssignmentId,
  'assignedAt' : Timestamp,
  'role' : IDL.Text,
  'personnelId' : PersonnelId,
  'projectId' : ProjectId,
  'personnelName' : IDL.Text,
  'companyId' : CompanyId,
});
export const ProjectCostId = IDL.Text;
export const ProjectCost = IDL.Record({
  'id' : ProjectCostId,
  'title' : IDL.Text,
  'createdAt' : Timestamp,
  'createdBy' : IDL.Text,
  'description' : IDL.Text,
  'projectId' : ProjectId,
  'currency' : IDL.Text,
  'category' : IDL.Text,
  'amount' : IDL.Float64,
  'companyId' : CompanyId,
});
export const Project = IDL.Record({
  'id' : ProjectId,
  'status' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'description' : IDL.Text,
  'deadline' : IDL.Text,
  'companyId' : CompanyId,
});
export const ShipmentId = IDL.Text;
export const Shipment = IDL.Record({
  'id' : ShipmentId,
  'status' : IDL.Text,
  'title' : IDL.Text,
  'shipDate' : IDL.Text,
  'createdAt' : Timestamp,
  'estimatedDelivery' : IDL.Text,
  'toLocation' : IDL.Text,
  'fromLocation' : IDL.Text,
  'notes' : IDL.Text,
  'carrier' : IDL.Text,
  'machineId' : IDL.Text,
  'companyId' : CompanyId,
});
export const TaskId = IDL.Nat;
export const AssigneeId = IDL.Text;
export const DeadLine = IDL.Text;
export const Task = IDL.Record({
  'id' : TaskId,
  'status' : IDL.Text,
  'title' : IDL.Text,
  'assigneeId' : AssigneeId,
  'dueDate' : DeadLine,
  'projectId' : ProjectId,
  'companyId' : CompanyId,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addDocument' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'addFailure' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'addHseRecord' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'addMachine' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'addMaintenancePlan' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'addPersonnelToCompany' : IDL.Func([IDL.Text, Code, IDL.Text], [], []),
  'addProjectCost' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Float64,
        IDL.Text,
        IDL.Text,
        IDL.Text,
      ],
      [IDL.Text],
      [],
    ),
  'addShipment' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
      ],
      [IDL.Text],
      [],
    ),
  'addTask' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'assignPersonnelToProject' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'authenticate' : IDL.Func([Code], [IDL.Opt(AuthenticatedUser)], ['query']),
  'createProject' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'deleteDocument' : IDL.Func([IDL.Text], [], []),
  'deleteMachine' : IDL.Func([IDL.Text], [], []),
  'deleteProjectCost' : IDL.Func([IDL.Text], [], []),
  'deleteTask' : IDL.Func([IDL.Nat], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getFailureMaintenance' : IDL.Func([IDL.Text], [IDL.Text], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'linkFailureMaintenance' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'listCompanyPersonnel' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(Personnel)],
      ['query'],
    ),
  'listDocuments' : IDL.Func([IDL.Text], [IDL.Vec(Document)], ['query']),
  'listFailures' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(FailureWithProject)],
      ['query'],
    ),
  'listHseRecords' : IDL.Func([IDL.Text], [IDL.Vec(HseRecord)], ['query']),
  'listMachines' : IDL.Func([IDL.Text], [IDL.Vec(Machine)], ['query']),
  'listMaintenancePlans' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(MaintenancePlan)],
      ['query'],
    ),
  'listProjectAssignments' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(ProjectAssignment)],
      ['query'],
    ),
  'listProjectCosts' : IDL.Func([IDL.Text], [IDL.Vec(ProjectCost)], ['query']),
  'listProjects' : IDL.Func([IDL.Text], [IDL.Vec(Project)], ['query']),
  'listShipments' : IDL.Func([IDL.Text], [IDL.Vec(Shipment)], ['query']),
  'listTasks' : IDL.Func([IDL.Text], [IDL.Vec(Task)], ['query']),
  'registerCompany' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Record({ 'id' : CompanyId, 'adminCode' : Code })],
      [],
    ),
  'removePersonnelFromProject' : IDL.Func([IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'selfRegisterPersonnel' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Record({ 'loginCode' : Code, 'inviteCode' : Code })],
      [],
    ),
  'updateFailureStatus' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'updateHseStatus' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'updateMachine' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'updateMachineStatus' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'updateMaintenancePlanStatus' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'updateProjectStatus' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'updateShipmentStatus' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'updateTaskStatus' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'addSupplier' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text], [IDL.Text], []),
  'deletePersonnel' : IDL.Func([IDL.Text], [], []),
  'deleteSupplier' : IDL.Func([IDL.Text], [], []),
  'listAllTasks' : IDL.Func([IDL.Text], [IDL.Vec(IDL.Record({'id':IDL.Nat,'projectId':IDL.Text,'companyId':IDL.Text,'title':IDL.Text,'status':IDL.Text,'assigneeId':IDL.Text,'dueDate':IDL.Text}))], ['query']),
  'listSuppliers' : IDL.Func([IDL.Text], [IDL.Vec(IDL.Record({'id':IDL.Text,'companyId':IDL.Text,'name':IDL.Text,'category':IDL.Text,'contactName':IDL.Text,'contactPhone':IDL.Text,'contactEmail':IDL.Text,'address':IDL.Text,'notes':IDL.Text,'status':IDL.Text,'createdAt':IDL.Int}))], ['query']),
  'resolveFailure' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'updatePersonnel' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'updateSupplier' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text], [], []),
  'updateSupplierStatus' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'updateTask' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Code = IDL.Text;
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const PersonnelId = IDL.Text;
  const CompanyId = IDL.Text;
  const AuthenticatedUser = IDL.Record({
    'role' : IDL.Opt(IDL.Text),
    'personnelId' : IDL.Opt(PersonnelId),
    'companyId' : IDL.Opt(CompanyId),
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'personnelId' : IDL.Opt(PersonnelId),
    'companyId' : IDL.Opt(CompanyId),
  });
  const Timestamp = IDL.Int;
  const Personnel = IDL.Record({
    'id' : PersonnelId,
    'loginCode' : Code,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'role' : IDL.Text,
    'inviteCode' : Code,
    'companyId' : IDL.Opt(CompanyId),
  });
  const DocumentId = IDL.Text;
  const Document = IDL.Record({
    'id' : DocumentId,
    'title' : IDL.Text,
    'createdAt' : Timestamp,
    'fileName' : IDL.Text,
    'category' : IDL.Text,
    'uploadedBy' : IDL.Text,
    'companyId' : CompanyId,
  });
  const FailureId = IDL.Text;
  const MachineId = IDL.Text;
  const FailureWithProject = IDL.Record({
    'id' : FailureId,
    'status' : IDL.Text,
    'title' : IDL.Text,
    'description' : IDL.Text,
    'reportedAt' : Timestamp,
    'reportedBy' : IDL.Text,
    'projectId' : IDL.Text,
    'severity' : IDL.Text,
    'machineId' : MachineId,
    'resolvedAt' : IDL.Text,
    'companyId' : CompanyId,
  });
  const HseId = IDL.Text;
  const HseRecord = IDL.Record({
    'id' : HseId,
    'status' : IDL.Text,
    'title' : IDL.Text,
    'hseType' : IDL.Text,
    'createdAt' : Timestamp,
    'description' : IDL.Text,
    'reportedBy' : IDL.Text,
    'severity' : IDL.Text,
    'companyId' : CompanyId,
  });
  const Machine = IDL.Record({
    'id' : MachineId,
    'status' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'serialNumber' : IDL.Text,
    'notes' : IDL.Text,
    'location' : IDL.Text,
    'machineType' : IDL.Text,
    'companyId' : CompanyId,
  });
  const MaintenancePlanId = IDL.Text;
  const MaintenancePlan = IDL.Record({
    'id' : MaintenancePlanId,
    'status' : IDL.Text,
    'title' : IDL.Text,
    'assignedTo' : IDL.Text,
    'createdAt' : Timestamp,
    'description' : IDL.Text,
    'frequency' : IDL.Text,
    'machineId' : IDL.Text,
    'nextDate' : IDL.Text,
    'companyId' : CompanyId,
  });
  const ProjectAssignmentId = IDL.Text;
  const ProjectId = IDL.Text;
  const ProjectAssignment = IDL.Record({
    'id' : ProjectAssignmentId,
    'assignedAt' : Timestamp,
    'role' : IDL.Text,
    'personnelId' : PersonnelId,
    'projectId' : ProjectId,
    'personnelName' : IDL.Text,
    'companyId' : CompanyId,
  });
  const ProjectCostId = IDL.Text;
  const ProjectCost = IDL.Record({
    'id' : ProjectCostId,
    'title' : IDL.Text,
    'createdAt' : Timestamp,
    'createdBy' : IDL.Text,
    'description' : IDL.Text,
    'projectId' : ProjectId,
    'currency' : IDL.Text,
    'category' : IDL.Text,
    'amount' : IDL.Float64,
    'companyId' : CompanyId,
  });
  const Project = IDL.Record({
    'id' : ProjectId,
    'status' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'description' : IDL.Text,
    'deadline' : IDL.Text,
    'companyId' : CompanyId,
  });
  const ShipmentId = IDL.Text;
  const Shipment = IDL.Record({
    'id' : ShipmentId,
    'status' : IDL.Text,
    'title' : IDL.Text,
    'shipDate' : IDL.Text,
    'createdAt' : Timestamp,
    'estimatedDelivery' : IDL.Text,
    'toLocation' : IDL.Text,
    'fromLocation' : IDL.Text,
    'notes' : IDL.Text,
    'carrier' : IDL.Text,
    'machineId' : IDL.Text,
    'companyId' : CompanyId,
  });
  const TaskId = IDL.Nat;
  const AssigneeId = IDL.Text;
  const DeadLine = IDL.Text;
  const Task = IDL.Record({
    'id' : TaskId,
    'status' : IDL.Text,
    'title' : IDL.Text,
    'assigneeId' : AssigneeId,
    'dueDate' : DeadLine,
    'projectId' : ProjectId,
    'companyId' : CompanyId,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addDocument' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'addFailure' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'addHseRecord' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'addMachine' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'addMaintenancePlan' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'addPersonnelToCompany' : IDL.Func([IDL.Text, Code, IDL.Text], [], []),
    'addProjectCost' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Float64,
          IDL.Text,
          IDL.Text,
          IDL.Text,
        ],
        [IDL.Text],
        [],
      ),
    'addShipment' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
        ],
        [IDL.Text],
        [],
      ),
    'addTask' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'assignPersonnelToProject' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'authenticate' : IDL.Func([Code], [IDL.Opt(AuthenticatedUser)], ['query']),
    'createProject' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'deleteDocument' : IDL.Func([IDL.Text], [], []),
    'deleteMachine' : IDL.Func([IDL.Text], [], []),
    'deleteProjectCost' : IDL.Func([IDL.Text], [], []),
    'deleteTask' : IDL.Func([IDL.Nat], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getFailureMaintenance' : IDL.Func([IDL.Text], [IDL.Text], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'linkFailureMaintenance' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'listCompanyPersonnel' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Personnel)],
        ['query'],
      ),
    'listDocuments' : IDL.Func([IDL.Text], [IDL.Vec(Document)], ['query']),
    'listFailures' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(FailureWithProject)],
        ['query'],
      ),
    'listHseRecords' : IDL.Func([IDL.Text], [IDL.Vec(HseRecord)], ['query']),
    'listMachines' : IDL.Func([IDL.Text], [IDL.Vec(Machine)], ['query']),
    'listMaintenancePlans' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(MaintenancePlan)],
        ['query'],
      ),
    'listProjectAssignments' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(ProjectAssignment)],
        ['query'],
      ),
    'listProjectCosts' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(ProjectCost)],
        ['query'],
      ),
    'listProjects' : IDL.Func([IDL.Text], [IDL.Vec(Project)], ['query']),
    'listShipments' : IDL.Func([IDL.Text], [IDL.Vec(Shipment)], ['query']),
    'listTasks' : IDL.Func([IDL.Text], [IDL.Vec(Task)], ['query']),
    'registerCompany' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Record({ 'id' : CompanyId, 'adminCode' : Code })],
        [],
      ),
    'removePersonnelFromProject' : IDL.Func([IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'selfRegisterPersonnel' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Record({ 'loginCode' : Code, 'inviteCode' : Code })],
        [],
      ),
    'updateFailureStatus' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'updateHseStatus' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'updateMachine' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'updateMachineStatus' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'updateMaintenancePlanStatus' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'updateProjectStatus' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'updateShipmentStatus' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'updateTaskStatus' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'addSupplier' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text], [IDL.Text], []),
    'deletePersonnel' : IDL.Func([IDL.Text], [], []),
    'deleteSupplier' : IDL.Func([IDL.Text], [], []),
    'listAllTasks' : IDL.Func([IDL.Text], [IDL.Vec(IDL.Record({'id':IDL.Nat,'projectId':IDL.Text,'companyId':IDL.Text,'title':IDL.Text,'status':IDL.Text,'assigneeId':IDL.Text,'dueDate':IDL.Text}))], ['query']),
    'listSuppliers' : IDL.Func([IDL.Text], [IDL.Vec(IDL.Record({'id':IDL.Text,'companyId':IDL.Text,'name':IDL.Text,'category':IDL.Text,'contactName':IDL.Text,'contactPhone':IDL.Text,'contactEmail':IDL.Text,'address':IDL.Text,'notes':IDL.Text,'status':IDL.Text,'createdAt':IDL.Int}))], ['query']),
    'resolveFailure' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'updatePersonnel' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'updateSupplier' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text], [], []),
    'updateSupplierStatus' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'updateTask' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text, IDL.Text], [], []),
    // Sürüm 28
    'addSupplierRating' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat, IDL.Text], [IDL.Text], []),
    'listSupplierRatings' : IDL.Func([IDL.Text], [IDL.Vec(IDL.Record({'id':IDL.Text,'supplierId':IDL.Text,'companyId':IDL.Text,'rating':IDL.Nat,'comment':IDL.Text,'createdAt':IDL.Int}))], ['query']),
    'getSupplierAverageRating' : IDL.Func([IDL.Text], [IDL.Opt(IDL.Nat)], ['query']),
    'deleteSupplierRating' : IDL.Func([IDL.Text], [], []),
    'addAttendance' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text], [IDL.Text], []),
    'listAttendance' : IDL.Func([IDL.Text], [IDL.Vec(IDL.Record({'id':IDL.Text,'companyId':IDL.Text,'personnelId':IDL.Text,'date':IDL.Text,'status':IDL.Text,'note':IDL.Text,'createdAt':IDL.Int}))], ['query']),
    'updateAttendance' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'deleteAttendance' : IDL.Func([IDL.Text], [], []),
    'addSparePart' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Nat, IDL.Text, IDL.Text], [IDL.Text], []),
    'listSpareParts' : IDL.Func([IDL.Text], [IDL.Vec(IDL.Record({'id':IDL.Text,'companyId':IDL.Text,'machineId':IDL.Text,'name':IDL.Text,'partCode':IDL.Text,'quantity':IDL.Nat,'unit':IDL.Text,'minStock':IDL.Nat,'supplier':IDL.Text,'notes':IDL.Text,'createdAt':IDL.Int}))], ['query']),
    'updateSparePart' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Nat, IDL.Text, IDL.Text], [], []),
    'deleteSparePart' : IDL.Func([IDL.Text], [], []),
  // Sürüm 30-B
    'addShift' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text], [IDL.Text], []),
    'listShifts' : IDL.Func([IDL.Text], [IDL.Vec(IDL.Record({'id':IDL.Text,'companyId':IDL.Text,'personnelId':IDL.Text,'shiftType':IDL.Text,'date':IDL.Text,'note':IDL.Text,'createdAt':IDL.Int}))], ['query']),
    'updateShift' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Text], [], []),
    'deleteShift' : IDL.Func([IDL.Text], [], []),
  // Sürüm 31-A
    'setProjectBudget' : IDL.Func([IDL.Text, IDL.Float64], [], []),
    'getProjectBudget' : IDL.Func([IDL.Text], [IDL.Opt(IDL.Float64)], ['query']),
    });
};

export const init = ({ IDL }) => { return []; };