/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type PersonnelId = string;
export type Timestamp = bigint;
export interface Shipment {
    id: ShipmentId;
    status: string;
    title: string;
    shipDate: string;
    createdAt: Timestamp;
    estimatedDelivery: string;
    toLocation: string;
    fromLocation: string;
    notes: string;
    carrier: string;
    machineId: string;
    companyId: CompanyId;
}
export type MaintenancePlanId = string;
export interface Document {
    id: DocumentId;
    title: string;
    createdAt: Timestamp;
    fileName: string;
    category: string;
    uploadedBy: string;
    companyId: CompanyId;
}
export interface Task {
    id: TaskId;
    status: string;
    title: string;
    assigneeId: AssigneeId;
    dueDate: DeadLine;
    projectId: ProjectId;
    companyId: CompanyId;
}
export interface ProjectCost {
    id: ProjectCostId;
    title: string;
    createdAt: Timestamp;
    createdBy: string;
    description: string;
    projectId: ProjectId;
    currency: string;
    category: string;
    amount: number;
    companyId: CompanyId;
}
export type ProjectAssignmentId = string;
export interface ProjectAssignment {
    id: ProjectAssignmentId;
    assignedAt: Timestamp;
    role: string;
    personnelId: PersonnelId;
    projectId: ProjectId;
    personnelName: string;
    companyId: CompanyId;
}
export type FailureId = string;
export type Code = string;
export type DocumentId = string;
export interface FailureWithProject {
    id: FailureId;
    status: string;
    title: string;
    description: string;
    reportedAt: Timestamp;
    reportedBy: string;
    projectId: string;
    severity: string;
    machineId: MachineId;
    resolvedAt: string;
    companyId: CompanyId;
}
export interface Personnel {
    id: PersonnelId;
    loginCode: Code;
    name: string;
    createdAt: Timestamp;
    role: string;
    inviteCode: Code;
    companyId?: CompanyId;
}
export interface HseRecord {
    id: HseId;
    status: string;
    title: string;
    hseType: string;
    createdAt: Timestamp;
    description: string;
    reportedBy: string;
    severity: string;
    companyId: CompanyId;
}
export type AssigneeId = string;
export type MachineId = string;
export interface Machine {
    id: MachineId;
    status: string;
    name: string;
    createdAt: Timestamp;
    serialNumber: string;
    notes: string;
    location: string;
    machineType: string;
    companyId: CompanyId;
}
export type ShipmentId = string;
export type CompanyId = string;
export interface AuthenticatedUser {
    role?: string;
    personnelId?: PersonnelId;
    companyId?: CompanyId;
}
export interface MaintenancePlan {
    id: MaintenancePlanId;
    status: string;
    title: string;
    assignedTo: string;
    createdAt: Timestamp;
    description: string;
    frequency: string;
    machineId: string;
    nextDate: string;
    companyId: CompanyId;
}
export type HseId = string;
export type TaskId = bigint;
export type ProjectId = string;
export interface Project {
    id: ProjectId;
    status: string;
    name: string;
    createdAt: Timestamp;
    description: string;
    deadline: string;
    companyId: CompanyId;
}
export type DeadLine = string;
export type ProjectCostId = string;
export interface UserProfile {
    name: string;
    email: string;
    personnelId?: PersonnelId;
    companyId?: CompanyId;
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addDocument(companyId: string, title: string, fileName: string, category: string, uploadedBy: string): Promise<string>;
    addFailure(machineId: string, companyId: string, title: string, description: string, severity: string, reportedBy: string, projectId: string): Promise<string>;
    addHseRecord(companyId: string, hseType: string, title: string, description: string, severity: string, reportedBy: string): Promise<string>;
    addMachine(companyId: string, name: string, machineType: string, serialNumber: string, location: string, notes: string): Promise<string>;
    addMaintenancePlan(companyId: string, machineId: string, title: string, description: string, frequency: string, nextDate: string, assignedTo: string): Promise<string>;
    addPersonnelToCompany(adminCode: Code, inviteCode: Code, role: string): Promise<void>;
    addProjectCost(companyId: string, projectId: string, title: string, category: string, amount: number, currency: string, description: string, createdBy: string): Promise<string>;
    addShipment(companyId: string, title: string, machineId: string, fromLocation: string, toLocation: string, carrier: string, shipDate: string, estimatedDelivery: string, notes: string): Promise<string>;
    addTask(projectId: string, companyId: string, title: string, assigneeId: string, dueDate: string): Promise<bigint>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    assignPersonnelToProject(companyId: string, projectId: string, personnelId: string, role: string): Promise<string>;
    authenticate(code: Code): Promise<AuthenticatedUser | null>;
    createProject(companyId: string, name: string, description: string, deadline: string): Promise<string>;
    deleteDocument(documentId: string): Promise<void>;
    deleteMachine(machineId: string): Promise<void>;
    deleteProjectCost(costId: string): Promise<void>;
    deleteTask(taskId: bigint): Promise<void>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getFailureMaintenance(failureId: string): Promise<string>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    linkFailureMaintenance(failureId: string, maintenancePlanId: string): Promise<void>;
    listCompanyPersonnel(companyId: string): Promise<Array<Personnel>>;
    listDocuments(companyId: string): Promise<Array<Document>>;
    listFailures(companyId: string): Promise<Array<FailureWithProject>>;
    listHseRecords(companyId: string): Promise<Array<HseRecord>>;
    listMachines(companyId: string): Promise<Array<Machine>>;
    listMaintenancePlans(companyId: string): Promise<Array<MaintenancePlan>>;
    listProjectAssignments(projectId: string): Promise<Array<ProjectAssignment>>;
    listProjectCosts(companyId: string): Promise<Array<ProjectCost>>;
    listProjects(companyId: string): Promise<Array<Project>>;
    listShipments(companyId: string): Promise<Array<Shipment>>;
    listTasks(projectId: string): Promise<Array<Task>>;
    registerCompany(name: string, mode: string): Promise<{
        id: CompanyId;
        adminCode: Code;
    }>;
    removePersonnelFromProject(assignmentId: string): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    selfRegisterPersonnel(name: string, role: string, title: string): Promise<{
        loginCode: Code;
        inviteCode: Code;
    }>;
    updateFailureStatus(failureId: string, status: string): Promise<void>;
    updateHseStatus(hseId: string, status: string): Promise<void>;
    updateMachine(machineId: string, name: string, machineType: string, serialNumber: string, location: string, notes: string): Promise<void>;
    updateMachineStatus(machineId: string, status: string): Promise<void>;
    updateMaintenancePlanStatus(planId: string, status: string): Promise<void>;
    updateProjectStatus(projectId: string, status: string): Promise<void>;
    updateShipmentStatus(shipmentId: string, status: string): Promise<void>;
    updateTaskStatus(taskId: bigint, status: string): Promise<void>;
    addSupplier(companyId: string, name: string, category: string, contactName: string, contactPhone: string, contactEmail: string, address: string, notes: string): Promise<string>;
    deletePersonnel(personnelId: string): Promise<void>;
    deleteSupplier(supplierId: string): Promise<void>;
    listAllTasks(companyId: string): Promise<Array<Task>>;
    listSuppliers(companyId: string): Promise<Array<Supplier>>;
    resolveFailure(failureId: string, resolutionNote: string): Promise<void>;
    updatePersonnel(personnelId: string, name: string, role: string, title: string): Promise<void>;
    updateSupplier(supplierId: string, name: string, category: string, contactName: string, contactPhone: string, contactEmail: string, address: string, notes: string): Promise<void>;
    updateSupplierStatus(supplierId: string, status: string): Promise<void>;
    updateTask(taskId: bigint, title: string, assigneeId: string, dueDate: string): Promise<void>;
}
import type { AuthenticatedUser as _AuthenticatedUser, Code as _Code, CompanyId as _CompanyId, Personnel as _Personnel, PersonnelId as _PersonnelId, Timestamp as _Timestamp, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addDocument(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.addDocument(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addDocument(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async addFailure(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string, arg5: string, arg6: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.addFailure(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addFailure(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
            return result;
        }
    }
    async addHseRecord(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string, arg5: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.addHseRecord(arg0, arg1, arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addHseRecord(arg0, arg1, arg2, arg3, arg4, arg5);
            return result;
        }
    }
    async addMachine(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string, arg5: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.addMachine(arg0, arg1, arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addMachine(arg0, arg1, arg2, arg3, arg4, arg5);
            return result;
        }
    }
    async addMaintenancePlan(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string, arg5: string, arg6: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.addMaintenancePlan(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addMaintenancePlan(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
            return result;
        }
    }
    async addPersonnelToCompany(arg0: Code, arg1: Code, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addPersonnelToCompany(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addPersonnelToCompany(arg0, arg1, arg2);
            return result;
        }
    }
    async addProjectCost(arg0: string, arg1: string, arg2: string, arg3: string, arg4: number, arg5: string, arg6: string, arg7: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.addProjectCost(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addProjectCost(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7);
            return result;
        }
    }
    async addShipment(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string, arg5: string, arg6: string, arg7: string, arg8: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.addShipment(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addShipment(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
            return result;
        }
    }
    async addTask(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addTask(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addTask(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async assignPersonnelToProject(arg0: string, arg1: string, arg2: string, arg3: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.assignPersonnelToProject(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignPersonnelToProject(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async authenticate(arg0: Code): Promise<AuthenticatedUser | null> {
        if (this.processError) {
            try {
                const result = await this.actor.authenticate(arg0);
                return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.authenticate(arg0);
            return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async createProject(arg0: string, arg1: string, arg2: string, arg3: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createProject(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createProject(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async deleteDocument(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteDocument(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteDocument(arg0);
            return result;
        }
    }
    async deleteMachine(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteMachine(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteMachine(arg0);
            return result;
        }
    }
    async deleteProjectCost(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteProjectCost(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteProjectCost(arg0);
            return result;
        }
    }
    async deleteTask(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteTask(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteTask(arg0);
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFailureMaintenance(arg0: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getFailureMaintenance(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFailureMaintenance(arg0);
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async linkFailureMaintenance(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.linkFailureMaintenance(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.linkFailureMaintenance(arg0, arg1);
            return result;
        }
    }
    async listCompanyPersonnel(arg0: string): Promise<Array<Personnel>> {
        if (this.processError) {
            try {
                const result = await this.actor.listCompanyPersonnel(arg0);
                return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listCompanyPersonnel(arg0);
            return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async listDocuments(arg0: string): Promise<Array<Document>> {
        if (this.processError) {
            try {
                const result = await this.actor.listDocuments(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listDocuments(arg0);
            return result;
        }
    }
    async listFailures(arg0: string): Promise<Array<FailureWithProject>> {
        if (this.processError) {
            try {
                const result = await this.actor.listFailures(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listFailures(arg0);
            return result;
        }
    }
    async listHseRecords(arg0: string): Promise<Array<HseRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.listHseRecords(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listHseRecords(arg0);
            return result;
        }
    }
    async listMachines(arg0: string): Promise<Array<Machine>> {
        if (this.processError) {
            try {
                const result = await this.actor.listMachines(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listMachines(arg0);
            return result;
        }
    }
    async listMaintenancePlans(arg0: string): Promise<Array<MaintenancePlan>> {
        if (this.processError) {
            try {
                const result = await this.actor.listMaintenancePlans(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listMaintenancePlans(arg0);
            return result;
        }
    }
    async listProjectAssignments(arg0: string): Promise<Array<ProjectAssignment>> {
        if (this.processError) {
            try {
                const result = await this.actor.listProjectAssignments(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listProjectAssignments(arg0);
            return result;
        }
    }
    async listProjectCosts(arg0: string): Promise<Array<ProjectCost>> {
        if (this.processError) {
            try {
                const result = await this.actor.listProjectCosts(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listProjectCosts(arg0);
            return result;
        }
    }
    async listProjects(arg0: string): Promise<Array<Project>> {
        if (this.processError) {
            try {
                const result = await this.actor.listProjects(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listProjects(arg0);
            return result;
        }
    }
    async listShipments(arg0: string): Promise<Array<Shipment>> {
        if (this.processError) {
            try {
                const result = await this.actor.listShipments(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listShipments(arg0);
            return result;
        }
    }
    async listTasks(arg0: string): Promise<Array<Task>> {
        if (this.processError) {
            try {
                const result = await this.actor.listTasks(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listTasks(arg0);
            return result;
        }
    }
    async registerCompany(arg0: string, arg1: string): Promise<{
        id: CompanyId;
        adminCode: Code;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.registerCompany(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerCompany(arg0, arg1);
            return result;
        }
    }
    async removePersonnelFromProject(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removePersonnelFromProject(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removePersonnelFromProject(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n17(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n17(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async selfRegisterPersonnel(arg0: string, arg1: string, arg2: string): Promise<{
        loginCode: Code;
        inviteCode: Code;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.selfRegisterPersonnel(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.selfRegisterPersonnel(arg0, arg1, arg2);
            return result;
        }
    }
    async updateFailureStatus(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateFailureStatus(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateFailureStatus(arg0, arg1);
            return result;
        }
    }
    async updateHseStatus(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateHseStatus(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateHseStatus(arg0, arg1);
            return result;
        }
    }
    async updateMachine(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string, arg5: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateMachine(arg0, arg1, arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateMachine(arg0, arg1, arg2, arg3, arg4, arg5);
            return result;
        }
    }
    async updateMachineStatus(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateMachineStatus(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateMachineStatus(arg0, arg1);
            return result;
        }
    }
    async updateMaintenancePlanStatus(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateMaintenancePlanStatus(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateMaintenancePlanStatus(arg0, arg1);
            return result;
        }
    }
    async updateProjectStatus(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProjectStatus(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProjectStatus(arg0, arg1);
            return result;
        }
    }
    async updateShipmentStatus(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateShipmentStatus(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateShipmentStatus(arg0, arg1);
            return result;
        }
    }
    async updateTaskStatus(arg0: bigint, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTaskStatus(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTaskStatus(arg0, arg1);
            return result;
        }
    }
    async addSupplier(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string, arg5: string, arg6: string, arg7: string): Promise<string> {
        if (this.processError) { try { return await this.actor.addSupplier(arg0,arg1,arg2,arg3,arg4,arg5,arg6,arg7); } catch(e) { this.processError(e); throw new Error("unreachable"); } } else { return await this.actor.addSupplier(arg0,arg1,arg2,arg3,arg4,arg5,arg6,arg7); }
    }
    async deletePersonnel(arg0: string): Promise<void> {
        if (this.processError) { try { return await this.actor.deletePersonnel(arg0); } catch(e) { this.processError(e); throw new Error("unreachable"); } } else { return await this.actor.deletePersonnel(arg0); }
    }
    async deleteSupplier(arg0: string): Promise<void> {
        if (this.processError) { try { return await this.actor.deleteSupplier(arg0); } catch(e) { this.processError(e); throw new Error("unreachable"); } } else { return await this.actor.deleteSupplier(arg0); }
    }
    async listAllTasks(arg0: string): Promise<Array<Task>> {
        if (this.processError) { try { return await this.actor.listAllTasks(arg0); } catch(e) { this.processError(e); throw new Error("unreachable"); } } else { return await this.actor.listAllTasks(arg0); }
    }
    async listSuppliers(arg0: string): Promise<Array<Supplier>> {
        if (this.processError) { try { return await this.actor.listSuppliers(arg0); } catch(e) { this.processError(e); throw new Error("unreachable"); } } else { return await this.actor.listSuppliers(arg0); }
    }
    async resolveFailure(arg0: string, arg1: string): Promise<void> {
        if (this.processError) { try { return await this.actor.resolveFailure(arg0,arg1); } catch(e) { this.processError(e); throw new Error("unreachable"); } } else { return await this.actor.resolveFailure(arg0,arg1); }
    }
    async updatePersonnel(arg0: string, arg1: string, arg2: string, arg3: string): Promise<void> {
        if (this.processError) { try { return await this.actor.updatePersonnel(arg0,arg1,arg2,arg3); } catch(e) { this.processError(e); throw new Error("unreachable"); } } else { return await this.actor.updatePersonnel(arg0,arg1,arg2,arg3); }
    }
    async updateSupplier(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string, arg5: string, arg6: string, arg7: string): Promise<void> {
        if (this.processError) { try { return await this.actor.updateSupplier(arg0,arg1,arg2,arg3,arg4,arg5,arg6,arg7); } catch(e) { this.processError(e); throw new Error("unreachable"); } } else { return await this.actor.updateSupplier(arg0,arg1,arg2,arg3,arg4,arg5,arg6,arg7); }
    }
    async updateSupplierStatus(arg0: string, arg1: string): Promise<void> {
        if (this.processError) { try { return await this.actor.updateSupplierStatus(arg0,arg1); } catch(e) { this.processError(e); throw new Error("unreachable"); } } else { return await this.actor.updateSupplierStatus(arg0,arg1); }
    }
    async updateTask(arg0: bigint, arg1: string, arg2: string, arg3: string): Promise<void> {
        if (this.processError) { try { return await this.actor.updateTask(arg0,arg1,arg2,arg3); } catch(e) { this.processError(e); throw new Error("unreachable"); } } else { return await this.actor.updateTask(arg0,arg1,arg2,arg3); }
    }
    async addSupplierRating(arg0: string, arg1: string, arg2: bigint, arg3: string): Promise<string> {
        if (this.processError) { try { return await (this.actor as any).addSupplierRating(arg0,arg1,arg2,arg3); } catch(e) { this.processError(e); throw new Error("unreachable"); } } else { return await (this.actor as any).addSupplierRating(arg0,arg1,arg2,arg3); }
    }
    async listSupplierRatings(arg0: string): Promise<Array<any>> {
        if (this.processError) { try { return await (this.actor as any).listSupplierRatings(arg0); } catch(e) { this.processError(e); throw new Error("unreachable"); } } else { return await (this.actor as any).listSupplierRatings(arg0); }
    }
    async getSupplierAverageRating(arg0: string): Promise<bigint | null> {
        if (this.processError) { try { const r = await (this.actor as any).getSupplierAverageRating(arg0); return r.length > 0 ? r[0] : null; } catch(e) { this.processError(e); throw new Error("unreachable"); } } else { const r = await (this.actor as any).getSupplierAverageRating(arg0); return r.length > 0 ? r[0] : null; }
    }
    async deleteSupplierRating(arg0: string): Promise<void> {
        if (this.processError) { try { return await (this.actor as any).deleteSupplierRating(arg0); } catch(e) { this.processError(e); throw new Error("unreachable"); } } else { return await (this.actor as any).deleteSupplierRating(arg0); }
    }
    async addAttendance(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string): Promise<string> {
        if (this.processError) { try { return await (this.actor as any).addAttendance(arg0,arg1,arg2,arg3,arg4); } catch(e) { this.processError(e); throw new Error("unreachable"); } } else { return await (this.actor as any).addAttendance(arg0,arg1,arg2,arg3,arg4); }
    }
    async listAttendance(arg0: string): Promise<Array<any>> {
        if (this.processError) { try { return await (this.actor as any).listAttendance(arg0); } catch(e) { this.processError(e); throw new Error("unreachable"); } } else { return await (this.actor as any).listAttendance(arg0); }
    }
    async updateAttendance(arg0: string, arg1: string, arg2: string): Promise<void> {
        if (this.processError) { try { return await (this.actor as any).updateAttendance(arg0,arg1,arg2); } catch(e) { this.processError(e); throw new Error("unreachable"); } } else { return await (this.actor as any).updateAttendance(arg0,arg1,arg2); }
    }
    async deleteAttendance(arg0: string): Promise<void> {
        if (this.processError) { try { return await (this.actor as any).deleteAttendance(arg0); } catch(e) { this.processError(e); throw new Error("unreachable"); } } else { return await (this.actor as any).deleteAttendance(arg0); }
    }
    async addSparePart(arg0: string, arg1: string, arg2: string, arg3: string, arg4: bigint, arg5: string, arg6: bigint, arg7: string, arg8: string): Promise<string> {
        if (this.processError) { try { return await (this.actor as any).addSparePart(arg0,arg1,arg2,arg3,arg4,arg5,arg6,arg7,arg8); } catch(e) { this.processError(e); throw new Error("unreachable"); } } else { return await (this.actor as any).addSparePart(arg0,arg1,arg2,arg3,arg4,arg5,arg6,arg7,arg8); }
    }
    async listSpareParts(arg0: string): Promise<Array<any>> {
        if (this.processError) { try { return await (this.actor as any).listSpareParts(arg0); } catch(e) { this.processError(e); throw new Error("unreachable"); } } else { return await (this.actor as any).listSpareParts(arg0); }
    }
    async updateSparePart(arg0: string, arg1: string, arg2: string, arg3: bigint, arg4: string, arg5: bigint, arg6: string, arg7: string): Promise<void> {
        if (this.processError) { try { return await (this.actor as any).updateSparePart(arg0,arg1,arg2,arg3,arg4,arg5,arg6,arg7); } catch(e) { this.processError(e); throw new Error("unreachable"); } } else { return await (this.actor as any).updateSparePart(arg0,arg1,arg2,arg3,arg4,arg5,arg6,arg7); }
    }
    async deleteSparePart(arg0: string): Promise<void> {
        if (this.processError) { try { return await (this.actor as any).deleteSparePart(arg0); } catch(e) { this.processError(e); throw new Error("unreachable"); } } else { return await (this.actor as any).deleteSparePart(arg0); }
    }
    async addShift(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string): Promise<string> {
        if (this.processError) { try { return await (this.actor as any).addShift(arg0,arg1,arg2,arg3,arg4); } catch(e) { this.processError(e); throw new Error("unreachable"); } } else { return await (this.actor as any).addShift(arg0,arg1,arg2,arg3,arg4); }
    }
    async listShifts(arg0: string): Promise<Array<any>> {
        if (this.processError) { try { return await (this.actor as any).listShifts(arg0); } catch(e) { this.processError(e); throw new Error("unreachable"); } } else { return await (this.actor as any).listShifts(arg0); }
    }
    async updateShift(arg0: string, arg1: string, arg2: string, arg3: string): Promise<void> {
        if (this.processError) { try { return await (this.actor as any).updateShift(arg0,arg1,arg2,arg3); } catch(e) { this.processError(e); throw new Error("unreachable"); } } else { return await (this.actor as any).updateShift(arg0,arg1,arg2,arg3); }
    }
    async deleteShift(arg0: string): Promise<void> {
        if (this.processError) { try { return await (this.actor as any).deleteShift(arg0); } catch(e) { this.processError(e); throw new Error("unreachable"); } } else { return await (this.actor as any).deleteShift(arg0); }
    }
    async setProjectBudget(arg0: string, arg1: number): Promise<void> {
        if (this.processError) { try { return await (this.actor as any).setProjectBudget(arg0,arg1); } catch(e) { this.processError(e); throw new Error("unreachable"); } } else { return await (this.actor as any).setProjectBudget(arg0,arg1); }
    }
    async getProjectBudget(arg0: string): Promise<number | null> {
        if (this.processError) { try { const r = await (this.actor as any).getProjectBudget(arg0); return r.length > 0 ? Number(r[0]) : null; } catch(e) { this.processError(e); throw new Error("unreachable"); } } else { const r = await (this.actor as any).getProjectBudget(arg0); return r.length > 0 ? Number(r[0]) : null; }
    }
    async addTaskNote(arg0: string, arg1: string, arg2: string, arg3: string): Promise<string> {
        if (this.processError) { try { return await (this.actor as any).addTaskNote(arg0,arg1,arg2,arg3); } catch(e) { this.processError(e); throw new Error("unreachable"); } } else { return await (this.actor as any).addTaskNote(arg0,arg1,arg2,arg3); }
    }
    async listTaskNotes(arg0: string): Promise<Array<any>> {
        if (this.processError) { try { return await (this.actor as any).listTaskNotes(arg0); } catch(e) { this.processError(e); throw new Error("unreachable"); } } else { return await (this.actor as any).listTaskNotes(arg0); }
    }
    async listTaskPriorities(arg0: string): Promise<Array<[bigint, string]>> {
        if (this.processError) { try { return await (this.actor as any).listTaskPriorities(arg0); } catch(e) { this.processError(e); throw new Error("unreachable"); } } else { return await (this.actor as any).listTaskPriorities(arg0); }
    }
}
function from_candid_AuthenticatedUser_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AuthenticatedUser): AuthenticatedUser {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_Personnel_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Personnel): Personnel {
    return from_candid_record_n16(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n11(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_AuthenticatedUser]): AuthenticatedUser | null {
    return value.length === 0 ? null : from_candid_AuthenticatedUser_n4(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_PersonnelId]): PersonnelId | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_CompanyId]): CompanyId | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n10(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    email: string;
    personnelId: [] | [_PersonnelId];
    companyId: [] | [_CompanyId];
}): {
    name: string;
    email: string;
    personnelId?: PersonnelId;
    companyId?: CompanyId;
} {
    return {
        name: value.name,
        email: value.email,
        personnelId: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.personnelId)),
        companyId: record_opt_to_undefined(from_candid_opt_n8(_uploadFile, _downloadFile, value.companyId))
    };
}
function from_candid_record_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _PersonnelId;
    loginCode: _Code;
    name: string;
    createdAt: _Timestamp;
    role: string;
    inviteCode: _Code;
    companyId: [] | [_CompanyId];
}): {
    id: PersonnelId;
    loginCode: Code;
    name: string;
    createdAt: Timestamp;
    role: string;
    inviteCode: Code;
    companyId?: CompanyId;
} {
    return {
        id: value.id,
        loginCode: value.loginCode,
        name: value.name,
        createdAt: value.createdAt,
        role: value.role,
        inviteCode: value.inviteCode,
        companyId: record_opt_to_undefined(from_candid_opt_n8(_uploadFile, _downloadFile, value.companyId))
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    role: [] | [string];
    personnelId: [] | [_PersonnelId];
    companyId: [] | [_CompanyId];
}): {
    role?: string;
    personnelId?: PersonnelId;
    companyId?: CompanyId;
} {
    return {
        role: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.role)),
        personnelId: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.personnelId)),
        companyId: record_opt_to_undefined(from_candid_opt_n8(_uploadFile, _downloadFile, value.companyId))
    };
}
function from_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Personnel>): Array<Personnel> {
    return value.map((x)=>from_candid_Personnel_n15(_uploadFile, _downloadFile, x));
}
function to_candid_UserProfile_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n18(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_record_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    email: string;
    personnelId?: PersonnelId;
    companyId?: CompanyId;
}): {
    name: string;
    email: string;
    personnelId: [] | [_PersonnelId];
    companyId: [] | [_CompanyId];
} {
    return {
        name: value.name,
        email: value.email,
        personnelId: value.personnelId ? candid_some(value.personnelId) : candid_none(),
        companyId: value.companyId ? candid_some(value.companyId) : candid_none()
    };
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
